baseURL = "https://michael-markl.de"
languageCode = "en-us"
title = "Michael Markl"

[params]
  author = "Michael Markl"
  description = "PhD student in algorithmic game theory"
  favicon = "favicon.png"
  [[params.style]]
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.footer]]
    text = "Email"
    url = "mailto:marklmichael98@gmail.com"
  [[params.footer]]
    text = "GitHub"
    url = "https://github.com/michael-markl"
  [[params.footer]]
    text = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-markl-16bbb7164/"

[permalinks]
  blogs = "/blog/:year/:month/:slug/"
  blog = "/blog/:year/:month/:slug/"



[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
