baseURL = "https://michael-markl.de"
languageCode = "en-us"
title = "Michael Markl"

[params]
  author = "Michael Markl"
  description = "PhD student in algorithmic game theory"
  favicon = "favicon.png"
  [[params.style]]
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.footer]]
    text = "Email"
    url = "mailto:marklmichael98@gmail.com"
  [[params.footer]]
    text = "GitHub"
    url = "https://github.com/michael-markl"
  [[params.footer]]
    text = "LinkedIn"
    url = "https://www.linkedin.com/in/michael-markl-16bbb7164/"
    
[build]
  writeStats = true

[permalinks]
  blogs = "/blog/:year/:month/:slug/"
  blog = "/blog/:year/:month/:slug/"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/css/bootstrap.min.css"
    target = "assets/bootstrap.min.css"
  [[module.mounts]]
    source = "node_modules/katex/dist/katex.min.css"
    target = "assets/katex.min.css"
  [[module.mounts]]
    source = "node_modules/katex/dist/katex.min.js"
    target = "assets/katex.min.js"
  [[module.mounts]]
    source = "node_modules/katex/dist/contrib/auto-render.min.js"
    target = "assets/contrib/auto-render.min.js"
  [[module.mounts]]
    source = "node_modules/katex/dist/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@fontsource/roboto"
    target = "assets/fonts/roboto"
  [[module.mounts]]
    source = "node_modules/@fontsource/roboto/files"
    target = "static/files"
  [[module.mounts]]
    source = "node_modules/@fontsource/josefin-sans"
    target = "assets/fonts/josefin-sans"
  [[module.mounts]]
    source = "node_modules/@fontsource/josefin-sans/files"
    target = "static/files"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
